version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "recipesApi"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sergo"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"



