"""

Revision ID: 0c4c2d3496ca
Revises: d780642efea2
Create Date: 2024-07-25 02:22:07.965604

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '0c4c2d3496ca'
down_revision = 'd780642efea2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_image_id_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'image_recipe', ['image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_image_id_fkey', 'recipe', 'image_recipe', ['image_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
