"""

Revision ID: 135c3f620627
Revises: 670c2fb39718
Create Date: 2024-07-20 23:25:09.275907

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '135c3f620627'
down_revision = '670c2fb39718'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
