"""

Revision ID: 2fb5dee4f044
Revises: b1680e805ecb
Create Date: 2024-07-08 00:39:41.783027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb5dee4f044'
down_revision = 'b1680e805ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_user_recipe', 'rating', ['user_id', 'recipe_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_user_recipe', 'rating', type_='unique')
    # ### end Alembic commands ###
