"""

Revision ID: 670c2fb39718
Revises: c82451fecba5
Create Date: 2024-07-20 23:02:22.589220

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '670c2fb39718'
down_revision = 'c82451fecba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'image_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'image_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
