"""

Revision ID: a58749a0f48d
Revises: dfd695b543ec
Create Date: 2024-07-20 23:59:44.979218

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a58749a0f48d'
down_revision = 'dfd695b543ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('image_id', sa.String(length=255), nullable=True))
    op.drop_column('step', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('step', 'image_id')
    # ### end Alembic commands ###
