"""

Revision ID: c82451fecba5
Revises:
Create Date: 2024-07-20 22:58:36.121165

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c82451fecba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_recipe',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('total_time', sa.Interval(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_average_rating'), 'recipe', ['average_rating'], unique=False)
    op.create_index(op.f('ix_recipe_image_id'), 'recipe', ['image_id'], unique=False)
    op.create_index(op.f('ix_recipe_total_time'), 'recipe', ['total_time'], unique=False)
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.String(length=255), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_recipe_id'), 'ingredient', ['recipe_id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uniq_user_recipe')
    )
    op.create_index(op.f('ix_rating_recipe_id'), 'rating', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_rating_user_id'), 'rating', ['user_id'], unique=False)
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('step_time', sa.Interval(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_recipe_id'), 'step', ['recipe_id'], unique=False)
    op.create_table('image_step',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_step')
    op.drop_index(op.f('ix_step_recipe_id'), table_name='step')
    op.drop_table('step')
    op.drop_index(op.f('ix_rating_user_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_recipe_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_ingredient_recipe_id'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_recipe_total_time'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_image_id'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_average_rating'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_table('image_recipe')
    # ### end Alembic commands ###
