"""

Revision ID: dfd695b543ec
Revises: 135c3f620627
Create Date: 2024-07-20 23:28:58.703469

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'dfd695b543ec'
down_revision = '135c3f620627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_image_id_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'image_recipe', ['image_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_image_id_fkey', 'recipe', 'image_recipe', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
