"""

Revision ID: fb638365fcb7
Revises: 2fb5dee4f044
Create Date: 2024-07-09 00:21:24.596015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb638365fcb7'
down_revision = '2fb5dee4f044'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('step', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'image_url')
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
